worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    server {
        listen 80 default_server;
        server_name _;
        root /app;
        index index.php index.html;

        location / {
            autoindex on;
            autoindex_exact_size off;
            autoindex_localtime on;
        }

        location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }

        location /assets/ {
            autoindex on;
        }

        location /dist/ {
            autoindex on;
        }

        location /res/ {
            autoindex on;
        }

        location /docs/ {
            autoindex on;
        }

        location /java/ {
            autoindex on;
        }

        location /apps/ {
            autoindex on;
        }
    }
}
