#!/bin/lua

--[[
if option == "Nano Editor" then os.execute("nano") os.exit()
    elseif option == "---" then app.main()
    elseif option == "New" then app.new()
    elseif option == "Save" then app.save()
    elseif option == "File Explorer" then os.execute("dir") os.exit()
    elseif option == "Build Project" then os.execute("lua") os.exit()
    elseif option == "Download Libraries" then app.dpkg()
    elseif option == "Documentation" then
        graphics.display(graphics.BuildScreen({
            title = "SmartME Docs",
            back = { root = app.main },
            fields = {
                "\tLua is a lightweight, high-level programming language designed for embedded use in applications. It was created in Brazil in the early 1990s by Roberto Ierusalimschy, Luiz Henrique de Figueiredo, and Waldemar Celes. Lua is known for its simple syntax, small size, and speed, making it ideal for use in game development, embedded systems, and applications that require a scripting language. It supports procedural programming, object-oriented programming, functional programming, and data-driven programming. One of Lua’s key features is its ability to be easily integrated with other programming languages, especially C and C++, allowing developers to extend applications with custom functionality. Lua is widely used in game engines like Roblox, World of Warcraft, and Adobe Lightroom for scripting purposes.",
                { type = "item", label = "Lua docs", root = "open " .. app.proxy .. "www.lua.org/manual/5.4/" }
            }
        }))
    elseif option == "About" then
]]

local app = {
    version = "1.2",
    proxy = getAppProperty("MIDlet-Proxy") or "http://opentty.xyz/proxy.php?",
    mirror = "rwa.githubusercontent.com/mrlima4095/OpenTTY-J2ME/main/",
}

app.main = function ()
    local previous = graphics.getCurrent()
    local menu = graphics.new("screen", "SmartME SDK")
    local back = graphics.new("command", { label = "Back", type = "ok", priority = 1 })
    local open = graphics.new("command", { label = "Open", type = "ok", priority = 1 })

    graphics.append(menu, "Download Libraries")
    graphics.append(menu, "Documentation")
    graphics.append(menu, "About")
    graphics.addCommand(menu, back)
    graphics.addCommand(menu, open)
    graphics.handler(menu, { [back] = function () graphics.display(previous) os.exit(0) end, [open] = app.main_handler, [graphics.fire] = app.main_handler })
    graphics.display(menu)
end
app.main_handler = function (opt)
    if opt == "Download Libraries" then
    elseif opt == "Documentation" then
    elseif opt == "About" then
    end
end


os.setproc("name", "sdk")
app.main()