#!/bin/lua


local PASTEBIN_API = os.getenv("PASTEBIN_API")
local PROXY = os.getenv("REPO") or "opentty.xyz:31522"
local PROXY_HTTP = "http://opentty.xyz/proxy.php?"

local app = {}

app.GetFile = function ()
    local previous = graphics.getCurrent()
    local screen = graphics.new("screen", "PasteBin")
    local back = graphics.new("command", { label = "Back", type = "back", priority = 1 })
    local upload = graphics.new("command", { label = "Upload", type = "ok", priority = 1 })

    graphics.append(screen, { type = "field", label = "File to Upload", value = "" })
    graphics.addCommand(screen, back)
    graphics.addCommand(screen, upload)
    graphics.handler(screen, {
        [back] = function () graphics.display(previous) end,
        [upload] = function (file)
            local content = io.read(file)
            if not content or content == "" then
                graphics.display(graphics.new("alert", "PasteBin", "Empty content"))
                return
            end

            app.Paste(content)
        end
    })
end

app.Paste = function (content)
    local conn, i, o = socket.connect("socket://" .. PROXY)

    io.write("post https://pastebin.com/api/api_post.php api_dev_key=" .. PASTEBIN_API .. "&api_option=paste&api_paste_code=" .. content, o)
    local res = io.read(i)

    local previous = graphics.getCurrent()
    local alert = graphics.new("alert", "PasteBin", res)
    local back = graphics.new("command", { label = "Back", type = "back", priority = 1 })
    local copy = graphics.new("command", { label = "Copy", type = "ok", priority = 1 })

    graphics.addCommand(alert, back)
    graphics.addCommand(alert, copy)
    graphics.handler(alert, {
        [back] = app.main,
        [copy] = function ()
            print(res)
            os.exit(0)
        end
    })
    graphics.display(alert)

    pcall(io.close, conn, i, o)
end

app.GetPaste = function ()
    local previous = graphics.getCurrent()
    local screen = graphics.new("screen", "PasteBin")
    local back = graphics.new("command", { label = "Back", type = "back", priority = 1 })
    local search = graphics.new("command", { label = "Search", type = "ok", priority = 1 })

    graphics.append(screen, { type = "field", label = "Paste ID", value = "" })
    graphics.addCommand(screen, back)
    graphics.addCommand(screen, search)
    graphics.handler(screen, {
        [back] = function () graphics.display(previous) end,
        [search] = function (id)
            local content, status = socket.http.get(PROXY_HTTP .. "pastebin.com/raw/" .. id)

            if status == 404 then
                graphics.display(graphics.new("alert", "PasteBin", "Paste not found"))
            else
                local view = graphics.new("screen", "PasteBin")
                local save = graphics.new("command", { label = "Back", type = "back", priority = 1 })

                graphics.append(view, content)
                graphics.addCommand(view, back)
                graphics.addCommand(view, save)
                graphics.handler(view, {
                    [back] = app.main
                })
                graphics.display(view)
            end
        end
    })
end

app.handler = function (opt)
    if opt == "New Paste" then
    elseif opt == "Upload File" then
        app.GetFile()
    elseif opt == "View Paste" then
        app.GetPaste()
    elseif opt == "Config. PasteBin API KEY" then
    end
end

app.main = function ()
    local previous = graphics.getCurrent()
    local menu = graphics.new("list", "PasteBin")
    local back = graphics.new("command", { label = "Back", type = "back", priority = 1 })
    local select = graphics.new("command", { label = "Open", type = "ok", priority = 1 })

    if PASTEBIN_API then
        graphics.append(menu, "New Paste")
        graphics.append(menu, "View Paste")
    else
        graphics.append(menu, "Config. PasteBin API KEY")
        graphics.append(menu, "View Paste")
    end
    graphics.addCommand(menu, back)
    graphics.addCommand(menu, select)
    graphics.handler(menu, { [back] = function () graphics.display(previous) os.exit(0) end, [select] = app.handler, [graphics.fire] = app.handler })
    graphics.display(menu)
end

os.setproc("name", "pastebin")
app.main()