#!/bin/lua

local function whois(domain)
    local ok, conn, i, o = pcall(socket.connect, "socket://whois.iana.org:43")
    local response

    if ok then
        pcall(io.write, domain, o)
        ok, response = pcall(io.read, i)
        pcall(io.close, conn, i, o)
        
        if ok then
            return response
        else
            return "Server error!"
        end
    else
        return "Connection error!"
    end
end
local function ifconfig()
    local status, output = io.popen("ifconfig")
    if status == 200 and output ~= "null" then
        return output
    else
        return "Not connected"
    end
end

local function menu()
    graphics.display(graphics.BuildList({
        title = "Armitage Tools",
        back = { label = "Back", root = os.exit },
        button = {
            label = "Open",
            root = function (opt)
                
            end
        },

        fields = {
            "Connect",
            "Get Local Address",
            "WhoIS Search",
            "Port Scanner",
            "Ping a WebSite",
            "Ping a Server",
            "HTTPS Requester"
        }
    }))
end

os.setproc("name", "armitage")


if arg[1] == nil then menu()
elseif arg[1] == "whois" then
    if arg[2] then
        print(whois(arg[2]))
    else
        print("Usage: " .. arg[0] .. " whois [domain]")
        os.exit(2)
    end
end