#!/bin/lua

if os.execute("case thread (MIDlet) false") == 255 then
    print("Cannot run in Main Thread") os.exit(1)
end

while true do
    os.execute("gc")
    os.execute("sleep " .. (os.getenv("TIMEOUT_GC") or 10))
end