#!/bin/lua

local host = os.getpid("boxhost2")

local function menu()
    graphics.display(graphics.BuildList({
        title = "BoxME",
        back = { root = os.exit },
        button = {
            label = "Select",
            root = function (option)
                if option == "New Machine" then
                elseif option == "Start a Machine" then
                elseif option == "Settings" then
                elseif option == "About" then
                end
            end
        },

        fields = { "New Machine", "Start a Machine", "Settings", "About" }
    }))
end

local function main()
    if host == nil then error("BoxME service isn't running!") end

    if not arg[1] or arg[1] == "menu" then menu()
    else print(arg[0] .. ": " .. arg[1] .. ": not found") end
end

os.setproc()
main()