#!/bin/lua

--[[

[ Config ]

name=JBenchmark
version=1.3
description=Debuggers

api.version=1.16
api.require=lua 
api.error=execute [ JBenchmark ] Required OpenTTY API 1.16 or newer and Lua Runtime
api.match=minimum

config=execute 

]]

local app, args = {}, {}
local services = {
    ["x11-wm"] = { },
    ["system"] = { }
}


function app.dumpsys(service)

end



function app.shell()
    if #args < 2 or args[2] == "" then

    elseif args[2] == "dumpsys" then
        if args[3] == nil then
            for k,_ in services do app.dumpsys(k) end
        else app.dumpsys(3) end
    elseif args[2] == "su" then

    end
end

function app.connect() end

function app.main()
    for i = 1, #arg do args[i] = arg[i] end

    if #args == 0 or arg[1] == "" then

    elseif args[1] == "shell" then app.shell()
    elseif args[1] == "connect" then app.connect()

    elseif args[1] == "install" then

    elseif args[1] == "uninstall" then

    elseif args[1] == "start" then

    elseif args[1] == "stop" then

    elseif args[1] == "logcat" then

    else print("jdb: " .. args[1] .. ": not found") end
end

app.main()