#!/bin/lua

--[[

[ Config ]

name=JBenchmark
version=1.3
description=Debuggers

api.version=1.16
api.require=lua 
api.error=execute [ JBenchmark ] Required OpenTTY API 1.16 or newer and Lua Runtime
api.match=minimum

config=execute 

]]


local app = { _port = 31337 }

function app.start()

end

function app.connect(args)
    if args then
        
    else

    end
end
function app.shell(args)
    table.remove(app, 1)

    if #args < 1 then

    elseif args[1] == "su" then

    elseif args[1] == "dumpsys" then

    elseif args[1] == "" then

    else print(arg[0] .. ": shell: " .. args[1] .. ": not found") end
end
function app.install(args) end 
function app.uninstall(args) end
function app.logcat(args) end

function app.run() end

function app.main(args)
    if #args == 0 then
        print("usage: jdb []")
    elseif args[1] == "connect" then

    elseif args[1] == "shell" then app.shell(args)
    elseif args[1] == "start" then

    elseif args[1] == "stop" then

    elseif args[1] == "install" then

    elseif args[1] == "uninstall" then

    elseif args[1] == "logcat" then app.logcat()
    else
        print(arg[0] .. ": " .. args[1] .. ": not found")
    end
end

local args = {}
for i = 1, #arg do args[i] = arg[i] end

app.main(args)
