#!/bin/lua

local docker = {}
local conteiners = {
    -- { conteiner = "/home/conteiner", active = true }
}

if arg[1] == "--deamon" then os.setproc("name", "dockerd") else os.setproc("name", "docker") end

if arg[1] == nil or arg[1] == "help" then
elseif arg[1] == "--deamon" then
    os.setproc("collector", "execute rm /tmp/.docker; stop docker;")

    return function (payload, source, pid, id)
        if payload == "ps" then return conteiners
        end
    end
elseif arg[1] == "run" then
elseif arg[1] == "exec" then
elseif arg[1] == "ps" then
elseif arg[1] == "stop" then
else print("docker: '" .. arg[1] .. "' is not a docker command.\nSee 'docker --help'")

end
