#!/bin/lua

local lines = 10

if arg[1] then
    local content = io.read(arg[1])
    if content == nil then
        io.write("head: " .. arg[1] .. ": not found")
        os.exit(127)
    end

    local lines_table = {}
    local start = 1

    for i = 1, #content do
        if string.sub(content, i, i) == "\n" then
            table.insert(lines_table, string.sub(content, start, i - 1))
            start = i + 1
        end
    end

    if start <= #content then
        table.insert(lines_table, string.sub(content, start))
    end

    for i = 1, math.min(lines, #lines_table) do
        print(lines_table[i])
    end
else
    print("head [file]")
end