#!/bin/lua

local function clean(item)
    collectgarbage()
    graphics.setText(item, "Used Memory: " .. collectgarbage("count") .. "\.nFree Memory: " .. collectgarbage("free") .. "\.nTotal Memory: " .. collectgarbage("total"))
end
local function monitor()
    local screen = graphics.new("screen", "Monitor")
    local info = graphics.new("buffer", { label = "Memory Status:" })
    local back = graphics.new("command", {
        label = "Back", type = "back", priority = 1
    })
    local refresh = graphics.new("command", {
        label = "Refresh", type = "ok", priority = 1
    })
    local handler = {
        [back] = function()
            graphics.display(os.getenv("xterm"))
        end,
        [refresh] = function()
            clean(inf9)
        end
    }
    
    graphics.append(screen, info)
    graphics.addCommand(screen, back)
    graphics.addCommand(screen, refresh)
    graphics.handler(screen, handler)
end

os.setproc("name", "monitor")
monitor()