#!/bin/lua


local function monitor()
    graphics.display(graphics.BuildScreen({
        back = { label = "Back", root = os.exit },
        button = { label = "Refresh", root = function () os.execute("gc") monitor() end },

        fields = {
            {
                type = "text",
                label = "Memory Status:",
                value = "Used Memory: " .. collectgarbage("count") .. "\.nFree Memory: " .. collectgarbage("free") .. "\.nTotal Memory: " .. collectgarbage("total")
            }
        }
    }))
end

os.setproc("name", "monitor")
monitor()