#!/bin/lua

graphics.display(graphics.BuildList({
    title = "MIDlet Updater",
    back = { label = "Back", root = os.exit },
    button = {
        label = "Go",
        root = function (opt)
            if opt == "Check for Updates" then
                
            elseif opt == "Go to releases archive" then os.execute("open http://opentty.xyz/dist/versions") os.exit()
            elseif opt == "Download 1.16 (LTS)" then os.execute("open http://opentty.xyz/dist/versions/OpenTTY-1.16.jar") os.exit()
            else os.execute("open http://opentty.xyz/dist/OpenTTY.jar") os.exit() end
        end
    },

    fields = { "Check for Updates", "Go to releases archive", "Download 1.16 (LTS)", "Download (Beta)" }
}))