#!/bin/lua

if arg[1] then
    local content = io.read(arg[1])
    local len = tonumber(arg[2]) or 10
    local lines, index, last = {}, 1, 1

    for i = 1, #content do
        if string.sub(content, i, i) == "\n" then
            lines[index] = string.sub(content, last, i)
        end
    end

    if #content <= len then
        print(content)
    else
        local i = #lines
        while lines - len ~= i do
            print(lines[i])
            i = i - 1
        end
    end
else print("tail [file]") end