# OpenTTY Nginx Configuration
# /etc/nginx/nginx.conf

listen 80;
root /home/;
server_name OpenTTY;
worker_processes 1;
error_log /tmp/nginx-error.log;
access_log /tmp/nginx-access.log;
max_clients 10;
